# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_ap',
            new_name='updated_at',
        ),
    ]
